name: Rust

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - "**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: "recursive"
        fetch-depth: 1

    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: List
      working-directory: program
      run: cargo --list

    - name: Test help
      working-directory: program
      run: cargo test --help

    - name: Run tests
      working-directory: program
      run: cargo test --verbose
